### PR TITLE
Store path template in config file

### PR DESCRIPTION
**Pull request by timwis**
I'd like to improve error filtering in `server.js`, but that need exists outside of this feature, so I'll treat it as a refactor branch separately.

As I mentioned in slack, GitSheets does not currently support multiple datasets in a repo, so this feature doesn't either. For that reason it uses `.gitsheets/config`. Should be a relatively easy fix to support multiple datasets (albeit breaking changes to the API) but is a distinct feature from this one.

~~EDIT: Don't merge yet; found an issue~~

### CODE REVIEW

**Comment by timwis** [comment]
I've just discovered that the current import functionality will create a new tree that leaves out the `.gitsheets` subtree from the previous commit. Need to fix that before merging.

**Comment by timwis** [comment]
Sorted

**Comment by themightychris** [comment]
@timwis looks good, this ready to merge now?

**Comment by timwis** [comment]
yessir

**Pull request merged**
